name: Git tags
on:
  release:
    types:
      - released
      - edited
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
      - master
    paths-ignore:
      - '**'

jobs:
  actions-tagger:
    name: Actualise by version
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
